<?php
namespace App\Http\Controllers\Appointment;
use App\Http\Controllers\Controller; use Carbon\Carbon; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class RecurringAppointmentController extends Controller {
 public function createRecord(array $d){$id=DB::table('recurring_appointments')->insertGetId(['patient_id'=>$d['patient_id'],'doctor_id'=>$d['doctor_id'],'branch_id'=>$d['branch_id'],'repeat_type'=>$d['repeat_type']??$d['recurring_type']??'weekly','repeat_interval'=>(int)($d['repeat_interval']??$d['recurring_interval']??1),'repeat_days'=>isset($d['repeat_days'])?json_encode($d['repeat_days']):(isset($d['recurring_days'])?json_encode($d['recurring_days']):null),'start_date'=>$d['start_date']??$d['appointment_date'],'end_date'=>$d['end_date']??$d['recurring_until']??null,'note'=>$d['note']??$d['reason']??null,'status'=>'active']);return ['id'=>$id]+$d;}
 public function generate(array $r,$time='00:00',$minutes=30){$date=Carbon::parse($r['start_date']??$r['appointment_date']);$end=!empty($r['end_date'])?Carbon::parse($r['end_date']):$date->copy()->addMonths(6);$days=$r['repeat_days']??$r['recurring_days']??[];if(is_string($days))$days=json_decode($days,true)?:[];$ids=[];$count=0;$type=$r['repeat_type']??$r['recurring_type']??'weekly';while($date<=$end&&$count<100){if(!($type==='weekly'&&$days&&!in_array($date->dayOfWeek,$days))){$start=Carbon::parse($date->toDateString().' '.$time);if(!DB::table('appointment')->where('doctor_id',$r['doctor_id'])->where('appointment_date',$date->toDateString())->whereNotIn('status',['cancelled','completed','no_show'])->exists())$ids[]=DB::table('appointment')->insertGetId(['patient_id'=>$r['patient_id'],'doctor_id'=>$r['doctor_id'],'branch_id'=>$r['branch_id'],'recurring_id'=>$r['id'],'appointment_code'=>'REC'.substr((string)now()->getTimestampMs().count($ids),-9),'appointment_date'=>$date->toDateString(),'start_time'=>$start,'end_time'=>$start->copy()->addMinutes((int)$minutes),'status'=>'scheduled']);$count++;}$date=$type==='daily'?$date->addDays((int)($r['repeat_interval']??1)):($type==='monthly'?$date->addMonths((int)($r['repeat_interval']??1)):$date->addWeeks((int)($r['repeat_interval']??1)));}return $ids;}
 public function create(Request $r){try{$x=$this->createRecord($r->all());$this->generate($x,$r->input('start_time','00:00'),$r->input('duration_minutes',30));return response()->json($x);}catch(\Throwable $e){return response()->json(['message'=>$e->getMessage()],400);}}
 public function show($id){$x=DB::table('recurring_appointments')->where('id',$id)->first();return $x?response()->json($x):response()->json(['message'=>'Not found'],404);}
 public function update(Request $r,$id){try{$d=$r->only(['patient_id','doctor_id','branch_id','repeat_type','repeat_interval','repeat_days','start_date','end_date','note','status']);if(array_key_exists('repeat_days',$d))$d['repeat_days']=json_encode($d['repeat_days']);if($d)DB::table('recurring_appointments')->where('id',$id)->update($d+['updated_at'=>now()]);return response()->json(['success'=>true]);}catch(\Throwable $e){return response()->json(['message'=>$e->getMessage()],400);}}
 public function destroy($id){try{DB::table('recurring_appointments')->where('id',$id)->delete();return response()->json(['success'=>true]);}catch(\Throwable $e){return response()->json(['message'=>$e->getMessage()],400);}}
 public function patient($id){try{return response()->json(DB::table('recurring_appointments')->where('patient_id',$id)->get());}catch(\Throwable $e){return response()->json(['message'=>$e->getMessage()],400);}}
 public function doctor($id){try{return response()->json(DB::table('recurring_appointments')->where('doctor_id',$id)->get());}catch(\Throwable $e){return response()->json(['message'=>$e->getMessage()],400);}}
 public function children($id){try{return response()->json(DB::table('appointment')->where('recurring_id',$id)->orderBy('appointment_date')->get());}catch(\Throwable $e){return response()->json(['error'=>$e->getMessage()],500);}}
 public function cancelChild($id){try{DB::table('appointment')->where('id',$id)->update(['status'=>'cancelled']);return response()->json(['success'=>true]);}catch(\Throwable $e){return response()->json(['error'=>$e->getMessage()],500);}}
 public function cancelAll($id){try{DB::table('appointment')->where('recurring_id',$id)->update(['status'=>'cancelled']);return response()->json(['success'=>true]);}catch(\Throwable $e){return response()->json(['error'=>$e->getMessage()],500);}}
}
