<?php

namespace App\Http\Controllers\Role;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class RoleController extends Controller
{
    private function rows(?int $id=null){$sql='SELECT r.id,r.name,r.code,r.description,r.is_system_role,r.status,r.created_at,r.updated_at,COUNT(ur.id) AS user_count FROM role r LEFT JOIN user_role ur ON r.id=ur.role_id WHERE r.status = ?'.($id===null?'':' AND r.id = ?').' GROUP BY r.id,r.name,r.code,r.description,r.is_system_role,r.status,r.created_at,r.updated_at ORDER BY r.created_at DESC';return DB::select($sql,$id===null?['active']:['active',$id]);}
    public function index(){try{return response()->json(['message'=>'Roles fetched successfully','data'=>$this->rows()]);}catch(\Throwable $e){return $this->db($e);}}
    public function show($id){try{$rows=$this->rows((int)$id);return $rows?response()->json(['message'=>'Role fetched successfully','data'=>$rows[0]]):response()->json(['message'=>'Role not found'],404);}catch(\Throwable $e){return $this->db($e);}}
    public function store(Request $r){$name=$r->input('name');$code=$r->input('code');if(!$name||!$code)return response()->json(['message'=>'Role name and code are required'],400);try{if(DB::table('role')->where('code',$code)->exists())return response()->json(['message'=>'Role code already exists'],409);$id=DB::table('role')->insertGetId(['name'=>$name,'code'=>$code,'description'=>$r->input('description')?:null,'is_system_role'=>$r->boolean('is_system_role'),'status'=>'active']);return response()->json(['message'=>'Role created successfully','data'=>['id'=>$id]],201);}catch(\Throwable $e){return response()->json(['message'=>'Create role failed','error'=>$e->getMessage()],500);}}
    public function update(Request $r,$id){if(!$id||!$r->input('name'))return response()->json(['message'=>'Role ID and name are required'],400);try{$n=DB::table('role')->where('id',$id)->where('status','active')->update(['name'=>$r->input('name'),'description'=>$r->input('description')?:null,'updated_at'=>now()]);return $n?response()->json(['message'=>'Role updated successfully']):response()->json(['message'=>'Role not found or cannot be modified'],404);}catch(\Throwable $e){return $this->db($e);}}
    public function destroy($id){if(!$id)return response()->json(['message'=>'Role ID is required'],400);try{$role=DB::table('role')->where('id',$id)->first();if(!$role)return response()->json(['message'=>'Role not found'],404);if($role->is_system_role)return response()->json(['message'=>'System roles cannot be deleted'],400);if(DB::table('user_role')->where('role_id',$id)->count()>0)return response()->json(['message'=>'Cannot delete role that is assigned to users'],400);DB::table('role')->where('id',$id)->update(['status'=>'inactive','updated_at'=>now()]);return response()->json(['message'=>'Role deleted successfully']);}catch(\Throwable $e){return $this->db($e);}}
    public function permissions($id){try{$rows=DB::select('SELECT p.id,p.name,p.code,p.module_name,rp.granted_at FROM permission p LEFT JOIN role_permission rp ON p.id=rp.permission_id AND rp.role_id=? WHERE p.status=? ORDER BY p.module_name,p.name',[$id,'active']);return response()->json(['message'=>'Role permissions fetched successfully','data'=>$rows]);}catch(\Throwable $e){return $this->db($e);}}
    public function assignPermission(Request $r){$role=$r->input('role_id');$permission=$r->input('permission_id');if(!$role||!$permission)return response()->json(['message'=>'Role ID and permission ID are required'],400);try{if(DB::table('role_permission')->where('role_id',$role)->where('permission_id',$permission)->exists())return response()->json(['message'=>'Permission already assigned to this role'],400);DB::table('role_permission')->insert(['role_id'=>$role,'permission_id'=>$permission,'granted_at'=>now()]);return response()->json(['message'=>'Permission assigned successfully'],201);}catch(\Throwable $e){return response()->json(['message'=>'Assign permission failed','error'=>$e->getMessage()],500);}}
    public function removePermission(Request $r){$role=$r->input('role_id');$permission=$r->input('permission_id');if(!$role||!$permission)return response()->json(['message'=>'Role ID and permission ID are required'],400);try{$n=DB::table('role_permission')->where('role_id',$role)->where('permission_id',$permission)->delete();return $n?response()->json(['message'=>'Permission removed successfully']):response()->json(['message'=>'Permission assignment not found'],404);}catch(\Throwable $e){return $this->db($e);}}
    private function db(\Throwable $e){return response()->json(['message'=>'Database error','error'=>$e->getMessage()],500);}
}
